### ISSUE TITLE
Working Build?

### ISSUE THREAD

**Issue by brianjking** [IntrinsicLabsAI/OCRTool#1] opened 2023-08-06 17:29 UTC
The release doesn't seem to open

**Comment by a10y** [comment] 2023-08-08 21:06
Hey @brianjking , thanks for raising this! The issue is that GitHub releases will strip the executable flag from binaries uploaded to the release.
 
To get around that, I've gone and updated the release to be a ZIP file wrapping the binary. If you unzip the file and run the inner CLI tool, the first time you do this it will fail due to Apple's preventing unsigned code from executing. You'll need to go to `System Settings` -> `Privacy & Security` and where it says `"OCRTool" was blocked from use because it is not from an identified developer.` you'll need to select `Allow Anyway`.

![Screenshot 2023-08-08 at 4 56 47 PM](https://github.com/IntrinsicLabsAI/OCRTool/assets/332583/83166ca3-2402-4606-b969-960ec781d560)

After this, subsequent invocations of the CLI should work! As always if you're concerned about running unsigned binaries, you're welcome to open the project in XCode and build the CLI from source!

**Comment by a10y** [comment] 2023-08-11 16:40
Closing for now, please reopen if you continue to have issues

**Closed as completed by a10y** 2023-08-11 16:40 UTC
